### ISSUE TITLE
"rpc error" when applying Slack example

### ISSUE THREAD

**Issue by szymonpk** [humio/terraform-provider-humio#16]
Hi,

I am running `Terraform v0.12.29`, provider built from the latest commit `db52f22da5a80d7fad23ff9339f7e81870728c58`. My terraform code is one of your examples with proper hook:

```
resource "humio_notifier" "example_slack" {
  repository = "<my repository>"
  name       = "example_slack"
  entity     = "SlackNotifier"

  slack {
    url    = "<valid hook URL>"
    fields = {
      "Events String" = "{events_str}"
      "Query"         = "{query_string}"
      "Time Interval" = "{query_time_interval}"
    }
  }
}
```

I am getting following output:

```
humio_notifier.example_slack: Creating...

Error: rpc error: code = Unavailable desc = transport is closing
```

I am using Cloud Humio, I use valid token (it works with humioctl).

**Comment by filipgolonka** [comment]
@szymonpk I had the same problem, the reason was that I used incorrect `repository`. Also I encountered that notifier should be referenced by `notifier_id` and not `id` - see this PR: https://github.com/humio/terraform-provider-humio/pull/17

**Comment by szymonpk** [comment]
Thanks! ;-) I think we can close it then.
