### ISSUE TITLE
Set up CI and release workflows

### ISSUE THREAD

**Issue by SaaldjorMike** [humio/terraform-provider-humio#7]
Tests can be run with `TF_ACC=1 go test -v ./...` given that environment variables `HUMIO_ADDR` and `HUMIO_API_TOKEN` have been correctly configured and are pointing to a Humio instance that is up and running.

We should consider adding multi-arch release procedures from the get go.

**Comment by evenh** [comment]
How do you propose to run acceptance tests? A few suggetions:

- A special instance of Humio for that purpose (cloud, provided by Humio)
- Spinning up a local installation via Docker? May be slower to run acceptance tests, always starts with a known state. E.g. [testcontainers](https://github.com/testcontainers/testcontainers-go) or spun up outside of go tooling

**Comment by SaaldjorMike** [comment]
I think the best approach for now would be to rely the "all-in-one" container image we publish: https://hub.docker.com/r/humio/humio/
This includes also Zookeeper and Kafka.

Then we can decide later if we want to depend on an external cluster to run the tests against.

**Comment by evenh** [comment]
I've started on this, testing the "all-in-one" image approach. One issue I'm currently battling is having a stable `HUMIO_API_TOKEN`. Do you know if there is a possibility to have one hardcoded or provided by configuration (file/environment)?

**Comment by SaaldjorMike** [comment]
Maybe we can go with single user auth for this: https://docs.humio.com/docs/security/single-user-setup/
When using that, you know the user/password combination for the cluster. After the cluster is up and running you can call `/api/v1/login` with the user/password combination in the body, and the response should then give you a token. This token can then be used to grab the "api token" you see in the `/settings` page.

You might even be able to skip the part where you grab the "api token" and just use the "token" you get from `/api/v1/login`.
